name: Release Build

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Make script executable
        run: chmod +x key-intercept-test.sh

      - name: Run test script
        run: ./key-intercept-test.sh

  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(grep "export const version_number" key-intercept/index.ts | cut -d'"' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Linux Zip
        run: zip -r key-intercept-linux.zip key-intercept key-intercept-install.sh

      - name: Create Windows Zip
        run: zip -r key-intercept-windows.zip key-intercept key-intercept-install.ps1 key-intercept-CLICK-ME.bat

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.VERSION }}"
          name: "Release v${{ env.VERSION }}"
          files: |
            key-intercept-linux.zip
            key-intercept-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
